[package]
name = "fauna"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
nalgebra = "0.33.2"
rand = "0.8.5"
rapier3d = { version = "0.22.0", features = ["parallel", "simd-stable"] }
rayon = "1.10.0"

[profile.release]
codegen-units = 1
opt-level = 3
